teams_app/dashboards/urls.py
from django.urls import path
from .views import dashboards, create_board, sort_by_name, sort_by_date, search_board, edit_board, create_column, create_task, delete_board
from django.contrib.auth import views as auth_views

app_name = 'dashboards'
urlpatterns = [
    path('',  dashboards, name = 'dashboards'),
    path('create_board/',  create_board, name = 'create_board'),
    path('sort_by_name/', sort_by_name, name='sort_by_name'),
    path('sort_by_date/', sort_by_date, name='sort_by_date'),
    path('search_board', search_board, name = 'search_board'),
    path('edit_board/<int:board_pk>', edit_board, name='edit_board'),
    path('delete_board/<int:board_pk>', delete_board, name='delete_board'),
    path('create_column/<int:board_pk>', create_column, name='create_column'),
    path('create_task/<int:board_pk>/<int:column_pk>', create_task, name='create_task'),
]

teams_app/teams_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import  views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('dashboards/', include('dashboards.urls')),
]

teams_app/users/urls.py
from django.urls import path
from .views import log_in, index, sign_up, welcome
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('',  welcome, name = 'welcome'),
    path('log_in/', log_in, name='log_in'),
    path('sign_up/', sign_up, name='sign_up'),
]

teams_app/dashboards/models.py
from django.db import models
from django.utils import timezone


class Board(models.Model):

    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)
    create_date = models.DateField(default=timezone.now())

    def __str__(self):
        return  self.name


class Column(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    index = models.IntegerField()
    name = models.CharField(max_length=50)

    def __str__(self):
        return  "{}-{}".format(self.board.name, self.name)


class Task(models.Model):
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=280)
    create_date = models.DateField(default=timezone.now())

    def __str__(self):
        return "{}-{}-{}".format(self.column.board.name, self.column.name, self.title)

teams_app/dashboards/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Board, Column


def dashboards(request):
    user_starting_letter = str(request.user)[0].capitalize()
    all_boards = Board.objects.all()
    context = {'user_starting_letter':user_starting_letter, 'all_boards': all_boards}
    print('sl', user_starting_letter,'user', str(request.user), 'auth', str(request.user.is_authenticated), 'id', str(request.user.pk))
    return render(request, 'dashboards/dashboards.html', context)

def create_board(request):
    user_starting_letter = str(request.user)[0].capitalize()
    if request.method == 'POST':
        print("I am in post!")
        try:
            print("Creating Board!")
            board_name = request.POST['board_name']
            board = Board(name = board_name)
            board.save()
        except (KeyError):
            return render(request, 'dashboards/dashboard_form.html', {
                'error_message': "You did not type a board name!!",
                'user_starting_letter':user_starting_letter,
            })
        else:
            all_boards = Board.objects.all()
            context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
            return HttpResponseRedirect(reverse('dashboards:dashboards'))
    else :
        print("I am in get!")
        return render(request, 'dashboards/dashboard_form.html', {
            'user_starting_letter': user_starting_letter,
        })

def sort_by_name(request):
    all_boards = Board.objects.order_by('name')
    user_starting_letter = str(request.user)[0].capitalize()
    context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
    return render(request, 'dashboards/dashboards.html', context)

def sort_by_date(request):
    all_boards = Board.objects.order_by('create_date')
    user_starting_letter = str(request.user)[0].capitalize()
    context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
    return render(request, 'dashboards/dashboards.html', context)

def search_board(request):
    user_starting_letter = str(request.user)[0].capitalize()
    all_boards = Board.objects.all()
    try:
        board_name = request.POST['board_name']
        board = Board(name=board_name)
        all_boards = Board.objects.filter(name__icontains = board_name)
        context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
        print(str(all_boards[0].pk), str(type(all_boards[0].pk)))
        return render(request, 'dashboards/dashboards.html', context)
    except (KeyError):
        context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
        return render(request, 'dashboards/dashboards.html', context)

def edit_board(request, board_pk):
    board = Board.objects.filter(pk = str(board_pk))[0]
    all_columns = board.column_set.all()
    user_starting_letter = str(request.user)[0].capitalize()
    print(board.name)
    context = {'board': board, 'user_starting_letter':user_starting_letter, 'all_columns': all_columns}
    return render(request, 'dashboards/board.html', context)

def create_column(request, board_pk):
    print("in create column")
    board = Board.objects.filter(pk=str(board_pk))[0]
    user_starting_letter = str(request.user)[0].capitalize()
    try:
        column_name = request.POST['column_name']
        board.column_set.create(index=board_pk, name=column_name)
        board.save()
        all_columns = board.column_set.all()
        context = {'user_starting_letter': user_starting_letter, 'all_columns': all_columns, 'board': board}
        return render(request, 'dashboards/board.html', context)
    except (KeyError):
        all_columns = Column.objects.all()
        context = {'user_starting_letter': user_starting_letter, 'all_columns': all_columns, 'board': board}
        return render(request, 'dashboards/board.html', context)


def create_task(request, board_pk, column_pk):
    board = Board.objects.filter(pk = str(board_pk))[0]
    column = Column.objects.filter(pk=str(column_pk))[0]
    user_starting_letter = str(request.user)[0].capitalize()
    try:
        task_title = request.POST['task_title']
        task_description = request.POST['task_description']
        column.task_set.create(title=task_title, description=task_description)
        column.save()
        all_columns = board.column_set.all()
        context = {'user_starting_letter': user_starting_letter, 'all_columns': all_columns, 'board': board}
        return render(request, 'dashboards/board.html', context)
    except (KeyError):
        all_columns = board.column_set.all()
        context = {'user_starting_letter': user_starting_letter, 'all_columns': all_columns, 'board': board}
        return render(request, 'dashboards/board.html', context)

def delete_board(request, board_pk):
    user_starting_letter = str(request.user)[0].capitalize()
    board = Board(pk = str(board_pk))
    board.delete()
    all_boards = Board.objects.all()
    context = {'user_starting_letter': user_starting_letter, 'all_boards': all_boards}
    return render(request, 'dashboards/dashboards.html', context)

teams_app/dashboards/templates/dashboards/board.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome Page Teams Application</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
          <a href="{% url 'users:welcome'%}"><img class="navbar-brand img-responsive" src= "{% static 'users/images/logo.jpg' %}" alt="" width="50" height="40"></a>
          <h5 class="my-0 mr-md-auto p-2 text-dark"><a href="{% url 'users:welcome'%}">You are inside {{board.name}}</a></h5>
          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-center" href=""><span class="border border-primary rounded-circle p-3">{{user_starting_letter}}</span></a>
            <a class="p-2 text-dark" href="{% url 'dashboards:dashboards'%}">Back to dashboards</a>
            <!--<a class="p-2 text-dark" href="#">Enterprise</a>-->
            <!--<a class="p-2 text-dark" href="#">Support</a>-->
            <!--<a class="p-2 text-dark" href="#">Pricing</a>-->
          </nav>

          <form class="form-inline my-2 my-lg-0 ml-2" action="{% url 'dashboards:create_column' board.pk%}" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" placeholder="Column name" aria-label="Search" name = "column_name">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add column</button>
          </form>
        </div>
    </header>

    <main role="main">

      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for column in all_columns %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <!--<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">-->
                <div class="card-body">
                  <p class="card-text">{{column.name}}</p>
                  {% for task in column.task_set.all%}
                  <div class="col-md-12">
                  <div class="p-3 mb-2 bg-primary text-white">Task title : {{task.title}}</div>
                    <p class="bg-dark text-white">Task description : {{task.description}}</p>
                  </div>
                  {%endfor%}
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <form class="form-inline my-2 my-lg-0 ml-2" action="{% url 'dashboards:create_task' board.pk column.pk%}" method="post">
                          {% csrf_token %}
                          <input class="form-control mr-sm-2" type="text" placeholder="Task title" aria-label="task_title" name = "task_title">
                           <input class="form-control mr-sm-2" type="text" placeholder="Task description" aria-label="task_description" name = "task_description">
                          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add Task</button>
                        </form>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Application created by Cristhian Murcia &copy;</p>

      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"><\/script>')</script>
    <script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.6/holder.min.js"></script>
  </body>
</html>

teams_app/dashboards/templates/dashboards/dashboard_form.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome Page Teams Application</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
          <a href="{% url 'users:welcome'%}"><img class="navbar-brand img-responsive" src= "{% static 'users/images/logo.jpg' %}" alt="" width="50" height="40"></a>
          <h5 class="my-0 mr-md-auto p-2 text-dark"><a href="{% url 'users:welcome'%}">{{user_starting_letter}}</a></h5>
          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-center" href=""><span class="border border-primary rounded-circle p-3">{{user_starting_letter}}</span></a>
            <a class="p-2 text-dark" href="{% url 'users:welcome'%}">Home</a>
            <!--<a class="p-2 text-dark" href="#">Enterprise</a>-->
            <!--<a class="p-2 text-dark" href="#">Support</a>-->
            <!--<a class="p-2 text-dark" href="#">Pricing</a>-->
          </nav>
          <a class="btn btn-outline-primary ml-2" href="{% url 'users:sign_up'%}">Add Dashboard</a>
          <a class="btn btn-outline-primary ml-2" href="{% url 'users:sign_up'%}">Delete Dashboard</a>
        </div>
    </header>
    <div class="mx-auto w-25 bg-dark text-white rounded">
        <!--<form class="m-3 form-signin" method="post" action="{% url 'dashboards:dashboards'%}">-->
        <form class="m-3 form-signin" method="post">
            {% csrf_token %}
            <img class="mb-4 m-2" src= "{% static 'users/images/logo.jpg' %}" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Insert the name of your board</h1>

            <label for="board_name" class="sr-only">Board name</label>
            <input type="text" id="board_name" class="form-control" placeholder="Board name" name="board_name" required autofocus>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Create board</button>
            <p class="mt-5 mb-3 text-muted">&copy; Python Bootcamp Final Assignment</p>
            <p class="mt-5 mb-3 text-muted">&copy; Code written by Cristhian Murcia</p>
        </form>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>
  </body>
</html>

teams_app/dashboards/templates/dashboards/dashboards.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome Page Teams Application</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
          <a href="{% url 'users:welcome'%}"><img class="navbar-brand img-responsive" src= "{% static 'users/images/logo.jpg' %}" alt="" width="50" height="40"></a>
          <h5 class="my-0 mr-md-auto p-2 text-dark"><a href="{% url 'users:welcome'%}">{{user_starting_letter}}</a></h5>
          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-center" href=""><span class="border border-primary rounded-circle p-3">{{user_starting_letter}}</span></a>
            <a class="p-2 text-dark" href="{% url 'users:welcome'%}">Home</a>
            <!--<a class="p-2 text-dark" href="#">Enterprise</a>-->
            <!--<a class="p-2 text-dark" href="#">Support</a>-->
            <!--<a class="p-2 text-dark" href="#">Pricing</a>-->
          </nav>
          <a class="btn btn-outline-primary ml-2" href="{% url 'dashboards:create_board'%}">Add Dashboard</a>
          <a class="btn btn-outline-secondary ml-2" href="{% url 'dashboards:sort_by_name'%}">Sort by name</a>
          <a class="btn btn-outline-secondary ml-2" href="{% url 'dashboards:sort_by_date'%}">Sort by creation date</a>
          <form class="form-inline my-2 my-lg-0 ml-2" action="{% url 'dashboards:search_board'%}" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name = "board_name">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search board</button>
          </form>
        </div>
    </header>

    <main role="main">

      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for board in all_boards %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <!--<img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">-->
                <div class="card-body">
                  <p class="card-text">{{board.name}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'dashboards:edit_board' board.pk %}"><button type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'dashboards:edit_board' board.pk %}">View/Edit</button></a>
                      <a href="{% url 'dashboards:delete_board' board.pk %}"><button type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'dashboards:delete_board' board.pk %}">Delete</button></a>
                    </div>
                    <small class="text-muted">Created on {{board.create_date}}</small>
                  </div>
                </div>
              </div>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>This project was created by Cristhian Murcia &copy; and corresponds to the final project proposed by <a>Globant</a></p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"><\/script>')</script>
    <script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.6/holder.min.js"></script>
  </body>
</html>